set_global_assignment -entity "ClockDividerProcessor" -library "lib_ClockDividerProcessor" -name IP_TOOL_NAME "altera_pll"
set_global_assignment -entity "ClockDividerProcessor" -library "lib_ClockDividerProcessor" -name IP_TOOL_VERSION "22.1"
set_global_assignment -entity "ClockDividerProcessor" -library "lib_ClockDividerProcessor" -name IP_TOOL_ENV "mwpim"
set_global_assignment -library "lib_ClockDividerProcessor" -name SPD_FILE [file join $::quartus(sip_path) "ClockDividerProcessor.spd"]

set_global_assignment -library "lib_ClockDividerProcessor" -name MISC_FILE [file join $::quartus(sip_path) "ClockDividerProcessor_sim/ClockDividerProcessor.vo"]
